services:
  db:
    image: postgres:9.5
    container_name: ride_sharing_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=ride_sharing     # Database name
      - POSTGRES_USER=admins         # Admin user
      - POSTGRES_PASSWORD=admin      # Admin password
    ports:
      - "5433:5432"                  # Expose port 5432 to host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist DB data
    networks:
      - ride_sharing_network

  app:
    image: fastapi-app               # Replace with your app image (if you have one)
    container_name: dreamy_ganguly
    environment:
      - DATABASE_URL=postgresql://admins:admin@db:5432/ride_sharing  # Connection string
    depends_on:
      - db
    networks:
      - ride_sharing_network

volumes:
  postgres_data:

networks:
  ride_sharing_network:
    driver: bridge
